name: mo_wahaj_top
description: "A new Flutter project."

version: 1.4.4+5

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_inappwebview: ^6.0.0
  responsive_sizer: ^3.3.1
  flutter_local_notifications: ^17.2.2
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  firebase_analytics: ^11.3.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  cloud_firestore: ^5.4.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  url_launcher: ^6.3.0
  intl_phone_number_input: ^0.7.4
  pinput: ^4.0.0
  smooth_page_indicator: ^1.2.0+3
  firebase_auth: ^5.3.0
  flutter_exit_app: ^1.1.4
  google_maps_flutter: ^2.9.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/


